config/urls.py
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('pybo/', include('pybo.urls')),
    path('', include('common.urls')),  # '/' 에 해당되는 path
    path('camera/', include('camera.urls')),
    path('parking_lot/', include('parking_lot.urls')),
    path('logs/', include('log.urls')),
    path('visitor/', include('visitor.urls')),
    path('warning/', include('warning.urls')),
    path('residents/', include('residents.urls')),
    path('alarm/', include('alarm.urls')),
]
handler500 = 'common.views.handler500'
handler404 = 'common.views.page_not_found'

log/urls.py
from django.urls import path
from . import views

app_name = 'log'

urlpatterns = [
                  path('', views.index, name='index'),
              ]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py.
    path('',
         base_views.index, name='index'),
    path('<int:question_number>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_number>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_number>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_number>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_number>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_number>/',
         answer_views.answer_delete, name='answer_delete'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    top_fixed = models.BooleanField(verbose_name='top_fix', default=False)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

pybo/views/SendApi.py
import requests
import json
def send_api(API_HOST, path, method, headers, body):
    url = API_HOST + path
    try:
        if method == "GET":
            response = requests.get(url, headers=headers)

        elif method == "POST":
            response = requests.post(
                url,
                headers=headers,
                data=json.dumps(body, ensure_ascii=False).encode("utf8"),
            )

        elif method == "DELETE":
            response = requests.delete(
                url,
                headers=headers,
                data=json.dumps(body, ensure_ascii=False).encode("utf8"),
            )
        elif method == "PUT":

            response = requests.put(
                url,
                headers=headers,
                data=json.dumps(body, ensure_ascii=False).encode("utf8"),
            )

    except Exception as ex:
        print(ex)

pybo/views/answer_views.py
from django.shortcuts import render, redirect, resolve_url
from datetime import datetime
from .SendApi import send_api
import requests

base_url = 'http://3.34.74.107:8000'

headers = {
    # "Authorization": "ToKen 750b311fec4b7c0a2a023bd557a149fb1f3a5085",  # 토큰값
    "Content-Type": "application/json",
    "charset": "UTF-8",
    "Accept": "*/*",
}
body = {}


def answer_create(request, question_number):  # 댓글 생성
    now = datetime.now()
    iso_time = now.isoformat()
    if request.method == 'POST':
        if 'session' in request.COOKIES:
            session = {'session': request.COOKIES['session']}
            responses = requests.post(base_url + '/SessionData/', data=session)
            data = responses.json()

            body['content'] = request.POST.get('content')  # 내용
            body['create_date'] = iso_time  # 작성 시간
            body['creator'] = data['username']  # 작성자
            body['modify_date'] = None  # 수정 시간
            body['question_number'] = question_number  # 질문 번호

            send_api(base_url, "/answer/", "POST", headers, body)
            return redirect('pybo:detail', question_number=question_number)
        else:
            return redirect('common:login')


def answer_modify(request, answer_number):  # 댓글 수정
    now = datetime.now()
    iso_time = now.isoformat()
    req = requests.get(base_url + '/answer/')
    response = req.json()
    if request.method == 'GET':
        if 'session' in request.COOKIES:
            session = {'session': request.COOKIES['session']}
            responses = requests.post(base_url + '/SessionData/', data=session)
            data = responses.json()
            for x in range(len(response)):
                if answer_number == response[x]['answer_number']:  # 선택한 댓글 내용 불러오기
                    content = response[x]['content']
                    context = {
                        'username': data['username'],
                        'login_status': request.COOKIES.get('login_status'),
                        'content': content
                    }
                    return render(request, 'pybo/answer_form.html', context)
        else:
            return redirect('common:login')
    if request.method == "POST":
        if 'session' in request.COOKIES:
            body['content'] = request.POST.get('content')
            body['modify_date'] = iso_time
            send_api(base_url, f"/answer/{answer_number}", "PUT", headers, body)
            question_number = ''
            for x in range(len(response)):
                if answer_number == response[x]['answer_number']:
                    question_number = response[x]['question_number']
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_number=question_number), answer_number))
        else:
            return redirect('common:login')


def answer_delete(request, answer_number):
    if 'session' in request.COOKIES:
        req = requests.get(base_url + '/answer/')
        response = req.json()
        for x in range(len(response)):
            if answer_number == response[x]['answer_number']:
                question_number = response[x]['question_number']
                send_api(base_url, f"/answer/{answer_number}", "DELETE", headers, body)
                return redirect('pybo:detail', question_number=question_number)

    else:
        return redirect('common:login')

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
import requests
from datetime import datetime
from requests.exceptions import ConnectTimeout
from dateutil import parser
base_url = 'http://3.34.74.107:8000'


def qdata(question_number):
    try:
        req = requests.get(base_url + '/question/')
        response = req.json()

        for x in range(len(response)):
            id = response[x]['question_number']
            if id == question_number:
                subject = response[x]['subject']
                content = response[x]['content']
                create_date = response[x]['create_datetime']
                if not is_date_format(create_date):
                    create_date = parser.parse(create_date)
                    create_date = create_date.strftime("%Y년 %m월 %d일 %H시 %M분")
                creator = response[x]['creator']
                modify_date = response[x]['modify_datetime']
                if modify_date:
                    if not is_date_format(modify_date):
                        modify_date = parser.parse(modify_date)
                        modify_date = modify_date.strftime("%Y년 %m월 %d일 %H시 %M분")
                return id, subject, content, create_date, creator, modify_date
    except ConnectTimeout:
        id = None
        subject = None
        content = None
        create_date = None
        creator = None
        modify_date = None
        return id, subject, content, create_date, creator, modify_date


def adata(question_id):  # 댓글 정보 불러오기
    try:
        reqs = requests.get(base_url + '/answer/')
        responses = reqs.json()
        answer = []
        count = 0
        for x in range(len(responses)):
            setdata = {}
            if question_id == responses[x]['question_number']:  # 각 질문 별 댓글 처리
                count += 1
                setdata['answer_number'] = responses[x]['answer_number']  # 댓글 번호
                setdata['content'] = responses[x]['content']  # 내용
                setdata['create_date'] = responses[x]['create_date']  # 작성 날짜
                setdata['question_number'] = responses[x]['question_number']
                if not is_date_format(setdata['create_date']):
                    create_dates = parser.parse(setdata['create_date'])
                    create_date = create_dates.strftime("%Y년 %m월 %d일 %H시 %M분")
                    setdata['create_date'] = create_date
                setdata['creator'] = responses[x]['creator']
                setdata['modify_date'] = responses[x]['modify_date']
                if setdata['modify_date']:
                    if not is_date_format(setdata['modify_date']):
                        modify_dates = parser.parse(setdata['modify_date'])
                        modify_date = modify_dates.strftime("%Y년 %m월 %d일 %H시 %M분")
                        setdata['modify_date'] = modify_date
                answer.append(setdata)
    except ConnectTimeout:
        answer = None
        count = None

    return answer, count


def count(question_id):  # 질문 별 댓글 숫자 확인
    try:
        reqs = requests.get(base_url + '/answer/')
        responses = reqs.json()
        return sum(1 for data in responses if data['question_number'] == question_id)
    except ConnectTimeout:
        return None


def is_date_format(string):  # ISO 시간 값 확인
    try:
        datetime.strptime(string, "%Y년 %m월 %d일 %H시 %M분")
        return True
    except ValueError:
        return False


def change_datetime_format(date_string):  # ISO 시간 값을 년.월.일.시.분으로 변환
    if date_string:
        try:
            date_obj = parser.parse(date_string)
            return date_obj.strftime("%Y년 %m월 %d일 %H시 %M분")
        except ValueError:
            pass
    return date_string


def change():
    try:
        req = requests.get(base_url + '/question/')
        responses = req.json()
        sorted_data = []
        for data in responses:
            data['create_datetime'] = change_datetime_format(data['create_datetime'])
            data['modify_datetime'] = change_datetime_format(data['modify_datetime'])
            data['count'] = count(data['question_number'])
            sorted_data.append(data)

        sorted_data = sorted(sorted_data, key=lambda x: x['question_number'], reverse=True)
        return sorted_data
    except ConnectTimeout:
        return []


def index(request):
    if request.method == 'GET':

        page = request.GET.get('page', '1')  # 페이지
        kw = request.GET.get('kw', '')  # 검색어
        repon = change()

        new_list = []
        results = []
        for x in repon:
            new_dict = {k: v for k, v in x.items() if
                        k not in ['question_number', 'create_datetime', 'modify_datetime']}
            new_list.append(new_dict)
            if kw and any(kw in str(value) for value in new_dict.values()):
                results.append(x)

        if kw:
            repon = results
        else:
            repon = [dict(new_dict, **x) for new_dict, x in zip(new_list, repon)]

        paginator = Paginator(repon, 10)
        page_obj = paginator.get_page(page)

        if 'session' in request.COOKIES:
            session = {}
            session['session'] = request.COOKIES['session']
            responses = requests.post(base_url + '/SessionData/', data=session)
            data = responses.json()

            context = {'question_list': page_obj,
                       'page': page,
                       'kw': kw,
                       'username': data['username']
                       }
            return render(request, 'pybo/question_list.html', context)
        else:
            return redirect('common:login')


def detail(request, question_number):
    if request.method == 'GET':

        answer, count = adata(question_number)
        id, subject, content, create_date, creator, modify_date = qdata(question_number)

        if 'session' in request.COOKIES:
            body = {'session': request.COOKIES['session']}
            responses = requests.post(base_url + '/SessionData/', data=body)
            data = responses.json()
            context = {'question_number': id,
                       'question_subject': subject,
                       'question_content': content,
                       'question_modify_date': modify_date,
                       'question_creator': creator,
                       'question_create_date': create_date,
                       'AnswerAll': answer,
                       'Answer_count': count,
                       'username': data['username']
                       }
            return render(request, 'pybo/question_detail.html', context)
        else:
            return redirect('common:login')

pybo/views/question_views.py
from django.shortcuts import render, redirect, resolve_url
from .SendApi import send_api
from datetime import datetime
import requests

base_url = 'http://3.34.74.107:8000'
headers = {
    # "Authorization": "ToKen 750b311fec4b7c0a2a023bd557a149fb1f3a5085",  # 토큰값
    "Content-Type": "application/json",
    "charset": "UTF-8",
    "Accept": "*/*",
}


def question_create(request):  # 질문 작성
    session = {'session': request.COOKIES['session']}
    responses = requests.post(base_url + '/SessionData/', data=session)
    data = responses.json()
    now = datetime.now()
    iso_time = now.isoformat()
    if request.method == 'GET':
        if 'session' in request.COOKIES:
            context = {
                'username': data['username']
            }
            return render(request, 'pybo/question_form.html', context)
        else:
            return redirect('common:login')

    if request.method == 'POST':
        if 'session' in request.COOKIES:
            body = {'subject': request.POST.get('subject'),
                    'content': request.POST.get('content'),
                    'create_datetime': iso_time,
                    'modify_datetime': None,
                    'creator': data['username'],
                    'etc': '공지'}
            send_api(base_url, "/question/", "POST", headers, body)
            return redirect('pybo:index')
        else:
            return redirect('common:login')


def question_modify(request, question_number):  # 질문 수정
    now = datetime.now()
    iso_time = now.isoformat()
    req = requests.get(base_url + '/question/')
    response = req.json()
    if request.method == 'GET':
        if 'session' in request.COOKIES:
            session = {'session': request.COOKIES['session']}
            responses = requests.post(base_url + '/SessionData/', data=session)
            data = responses.json()
            for x in range(len(response)):
                if question_number == response[x]['question_number']:
                    subject = response[x]['subject']
                    content = response[x]['content']
                    context = {
                        'username': data['username'],
                        'form_subject': subject,
                        'form_content': content,

                    }
                    return render(request, 'pybo/question_form.html', context)
        else:
            return redirect('common:login')
    if request.method == "POST":
        if 'session' in request.COOKIES:

            body = {'subject': request.POST.get('subject'),
                    'content': request.POST.get('content'),
                    'modify_datetime': iso_time}
            print(body)
            send_api(base_url, f"/question/{question_number}", "PUT", headers, body)

            return redirect('/pybo/{}/#question_{}'.format(question_number, question_number))
        else:
            return redirect('common:login')


def question_delete(request, question_number):  # 질문 삭제
    if 'session' in request.COOKIES:
        body = {}
        send_api(base_url, f"/question/{question_number}", "DELETE", headers, body)
        return redirect('pybo:index')
    else:
        return redirect('common:login')

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ content|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question_subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" >{{ question_content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if question_modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">수정 시간</div>
                    <div>{{ question_modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">작성자 : {{ question_creator }}</div>
                    <div>{{ question_create_date }}</div>
                </div>
            </div>
            <div class="my-3">
            <a href="{% url 'pybo:question_modify' question_number  %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
               data-uri="{% url 'pybo:question_delete' question_number  %}">삭제</a>
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{Answer_count}}개의 답변이 있습니다.</h5>
    {% for answer in AnswerAll %}
    <a id="answer_{{ answer.answer_number }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" >{{ answer.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">수정 시간</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">작성자 : {{ answer.creator }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
            <a href="{% url 'pybo:answer_modify' answer.answer_number  %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
               <a href="#" class="delete btn btn-sm btn-outline-secondary "
               data-uri="{% url 'pybo:answer_delete' answer.answer_number %}">삭제</a>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question_number %}" method="post" class="my-3">
        {% csrf_token %}
           <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
        <label for="content" class="form-label">답변내용</label>
        <textarea
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
          <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form_subject|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form_content|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}
{% block script %}
<script>
    var checkUnload = true;
    $(window).on('beforeunload', function () {
        if (checkUnload) return "이 페이지를 벗어나면 작성된 내용은 저장되지 않습니다.";
    });
    $("#write").on("click", function () {
        checkUnload = false;
        $("submit").submit();
    });
</script>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <h2 class="border-bottom py-2">공지사항 & 건의사항</h2>
        <div class="col-6">
            <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        {% if question.etc == '공지' %}
            <tr class="text-center" bgcolor="#D9E5FF">
        {% else %}
            <tr class="text-center">
        {% endif %}
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start" style="margin-left: 3%">
                <a href="{% url 'pybo:detail' question.question_number %}">({{ question.etc }}) {{ question.subject }}</a>
                {% if question.count > 0 %}
                <span class="text-danger small mx-2">{{ question.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.creator }}</td>  <!-- 글쓴이 추가 -->
            <td>{{ question.create_datetime }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr class = "text-center">
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
 <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center" >
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
            href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}

        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}"
           href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->

</div>
<form id="searchForm" method="get" action="{% url 'pybo:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
document.getElementById("search_kw").addEventListener("keyup", function(event) {
        if (event.keyCode === 13) {
            event.preventDefault();
            document.getElementById("btn_search").click();
        }
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}