common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.login_api, name='login'),
    path('login/', views.login_api),
    path('logout', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('pybo/', include('pybo.urls')),
    path('', include('common.urls')),  # '/' 에 해당되는 path
    path('camera/', include('camera.urls')),
    path('parking_lot/', include('parking_lot.urls')),
    path('logs/', include('log.urls')),
    path('visitor/', include('visitor.urls')),
    path('warning/', include('warning.urls')),
    path('residents/', include('residents.urls')),
    path('alarm/', include('alarm.urls')),
]
handler500 = 'common.views.handler500'
handler404 = 'common.views.page_not_found'

log/urls.py
from django.urls import path
from . import views

app_name = 'log'

urlpatterns = [
                  path('', views.index, name='index'),
              ]

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '15자 이내로 입력 가능합니다.'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'username': '닉네임',
            'email': '이메일',
            'password1': '패스워드'
        }
        # 글자수 제한

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['maxlength'] = 15

common/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from datetime import datetime
import requests
import re
from django.core.paginator import Paginator
from requests.exceptions import ConnectTimeout
import hashlib
from dateutil import parser

base_url = 'http://3.34.74.107:8000'
headers = {
    # "Authorization": "ToKen 750b311fec4b7c0a2a023bd557a149fb1f3a5085",  # 토큰값
    "Content-Type": "application/json",
    "charset": "UTF-8",
    "Accept": "*/*",
}
body = {}


def is_date_format(string):  # 시간 데이터 형식 확인
    try:
        datetime.strptime(string, "%Y년 %m월 %d일 %H시 %M분")
        return True
    except ValueError:
        return False


def change():
    try:
        reqs = requests.get(base_url + '/question/')
        responses = reqs.json()
        QData = responses
        sorted_data = []
        for x in range(len(QData)):
            create_date = QData[x]['create_datetime']
            if not is_date_format(create_date):
                create_date = parser.parse(create_date)
                create_date = create_date.strftime("%Y년 %m월 %d일 %H시 %M분")
            QData[x]['create_datetime'] = create_date
            QData[x]['count'] = Adata(QData[x]['question_number'])
            if QData:
                sorted_data = sorted(QData, key=lambda x: x['question_number'], reverse=True)
    except ConnectTimeout:
        sorted_data = []
    return sorted_data


def Adata(question_id):  # 각 질문 별 답 갯수 카운트
    try:
        reqx = requests.get(base_url + '/answer/')
        responsex = reqx.json()
        count = 0
        for x in range(len(responsex)):
            if question_id == responsex[x]['question_number']:
                count += 1
    except ConnectTimeout:
        count = None
    return count


def login_api(request):
    if request.method == 'GET':  # 세션 확인
        context = {'error_message': False}
        if 'session' in request.COOKIES:
            return redirect('pybo:index')
        else:
            return render(request, 'common/login.html', context)

    if request.method == "POST":
        data = {}
        # 폼에서 ID와 PW를 받아서 암호화
        login_ID = request.POST.get('login_ID')
        login_PassWd = request.POST.get('login_PassWd')
        hashed = hashlib.sha256()
        hashed.update(login_PassWd.encode('utf-8'))

        body['login_ID'] = login_ID
        body['login_PassWd'] = hashed.hexdigest()
        hashed.update(login_ID.encode('utf-8'))
        body['seesion'] = hashed.hexdigest()
        try:
            responses = requests.post(base_url + '/loginforAdministrator/', data=body)
            data = responses.json()
        except ConnectTimeout:
            data['error'] = "로그인 성공"
            data['session'] = ""
        if data['error']:
            if data['error'] == "로그인 성공":
                page = request.GET.get('page', '1')  # 페이지
                kw = request.GET.get('kw', '')  # 검색어
                respon = change()
                paginator = Paginator(respon, 10)
                page_obj = paginator.get_page(page)
                context = {
                    'question_list': page_obj,
                    'page': page,
                    'kw': kw,
                    'username': login_ID,
                }

                responses = render(request, 'pybo/question_list.html', context)
                responses.set_cookie('session', data['session'])
                return responses
            else:
                context = {'error_message': data['error']}
                return render(request, 'common/login.html', context)
        else:
            return render(request, 'common/login.html')


def logout(request):  # 세션 데이터 삭제
    response = HttpResponseRedirect('login')
    response.delete_cookie('session')

    return response


def signup(request):  # 회원 가입
    if request.method == 'GET':
        if 'session' in request.COOKIES:
            return redirect('pybo:index')
        else:
            return render(request, 'common/signup.html')

    if request.method == "POST":
        # 폼에서 ID,PW,email 받아오기
        context = {}
        respond = render(request, 'common/signup.html', context)
        login_ID = request.POST.get('username')
        login_PassWd = request.POST.get('password')
        email = request.POST.get('email')

        # 로그인 조건 ID는 15자 미만, PW는 특수문자 1개 이상,숫자 영어 혼용
        if not 8 <= len(login_ID) < 15:
            print('1')
            context = {'error_message': '아이디의 길이가 맞지 않습니다.'}
            return respond

        pattern = r"^(?=.*[!@#$%^&*(),.?\":{}|<>])(?=.*\d)(?=.*[a-zA-Z]).{8,19}$"
        if not re.match(pattern, login_PassWd):
            print('2')
            context = {'error_message': '비밀번호 형식이 맞지 않습니다.'}
            return respond
        # PW 암호화
        hashed_password = hashlib.sha256(login_PassWd.encode('utf-8')).hexdigest()
        hashed_session = hashlib.sha256(login_ID.encode('utf-8')).hexdigest()
        body = {'login_ID': login_ID, 'login_PassWd': hashed_password, 'email': email, 'session': hashed_session}

        response = requests.post(base_url + '/RegistUser/', data=body)
        data = response.json()
        print(data)
        if data.get('error'):
            context = {'error_message': data['error']}
            return respond

        page = request.GET.get('page', '1')  # 페이지
        kw = request.GET.get('kw', '')  # 검색어
        response_data = change()
        paginator = Paginator(response_data, 10)
        page_obj = paginator.get_page(page)
        context = {
            'question_list': page_obj,
            'page': page,
            'kw': kw,
            'username': login_ID,
        }

        response = render(request, 'pybo/question_list.html', context)
        response.set_cookie('session', data['session'])
        return response


def page_not_found(request, exception):
    if 'session' in request.COOKIES:  # 세션 여부 확인
        session = {}
        session['session'] = request.COOKIES['session']
        responses = requests.post(base_url + '/SessionData/', data=session)
        data = responses.json()
        context = {
            'username': data['username'],
        }
    return render(request, 'common/404.html', context)


def handler500(request):
    if 'session' in request.COOKIES:  # 세션 여부 확인
        session = {}
        session['session'] = request.COOKIES['session']
        responses = requests.post(base_url + '/SessionData/', data=session)
        data = responses.json()
        context = {
            'username': data['username'],
        }
    response = render(request, "common/500.html", context)
    response.status_code = 500
    return response

templates/common/login.html
{% extends "base.html" %}
{% block content %}
{% if error_message %}
    <div class="alert alert-danger" role="alert">
        <strong>로그인 오류:</strong> {{ error_message }}
    </div>
{% endif %}
    <div class="container justify-content-center mt-5" >
        <form method="post" action="{% url 'common:login' %}">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
            {% include "form_errors.html" %}
            <div class="mb-3">
                <label for="username">사용자ID</label>
                <input type="text" class="form-control" name="login_ID" id="login_ID"
                       value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password">비밀번호</label>
                <input type="password" class="form-control" name="login_PassWd" id="login_PassWd"
                       value="{{ form.password.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn btn-primary">로그인</button>
        </form>
    </div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% if error_message %}
            <div class="alert alert-danger" role="alert">
                <strong>회원가입 오류:</strong> {{ error_message }}
            </div>
        {% endif %}
        {% csrf_token %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username" placeholder="8자 이상 15자 미만으로 작성해주세요"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="8자 이상 20자 미만 영단어와 1개 이상의 특수기호, 숫자로 입력해주세요"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>

        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}