camera/urls.py
from django.urls import path
from . import views

app_name = 'camera'

urlpatterns = [
    path('', views.camera, name='camera'),
]

common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.login_api, name='login'),
    path('login/', views.login_api),
    path('logout', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('pybo/', include('pybo.urls')),
    path('', include('common.urls')),  # '/' 에 해당되는 path
    path('camera/', include('camera.urls')),
    path('parking_lot/', include('parking_lot.urls')),
    path('logs/', include('log.urls')),
    path('visitor/', include('visitor.urls')),
    path('warning/', include('warning.urls')),
    path('residents/', include('residents.urls')),
    path('alarm/', include('alarm.urls')),
]
handler500 = 'common.views.handler500'
handler404 = 'common.views.page_not_found'

log/urls.py
from django.urls import path
from . import views

app_name = 'log'

urlpatterns = [
                  path('', views.index, name='index'),
              ]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py.
    path('',
         base_views.index, name='index'),
    path('<int:question_number>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_number>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_number>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_number>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_number>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_number>/',
         answer_views.answer_delete, name='answer_delete'),
]

visitor/urls.py
from django.urls import path
from . import views

app_name = 'visitor'

urlpatterns = [
    path('', views.visitor, name='visitor'),
    path('delete/<int:visitor_information_number>/', views.delete, name='visitor_delete'),

]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
import requests
from datetime import datetime
from requests.exceptions import ConnectTimeout
from dateutil import parser
base_url = 'http://3.34.74.107:8000'


def qdata(question_number):
    try:
        req = requests.get(base_url + '/question/')
        response = req.json()

        for x in range(len(response)):
            id = response[x]['question_number']
            if id == question_number:
                subject = response[x]['subject']
                content = response[x]['content']
                create_date = response[x]['create_datetime']
                if not is_date_format(create_date):
                    create_date = parser.parse(create_date)
                    create_date = create_date.strftime("%Y년 %m월 %d일 %H시 %M분")
                creator = response[x]['creator']
                modify_date = response[x]['modify_datetime']
                if modify_date:
                    if not is_date_format(modify_date):
                        modify_date = parser.parse(modify_date)
                        modify_date = modify_date.strftime("%Y년 %m월 %d일 %H시 %M분")
                return id, subject, content, create_date, creator, modify_date
    except ConnectTimeout:
        id = None
        subject = None
        content = None
        create_date = None
        creator = None
        modify_date = None
        return id, subject, content, create_date, creator, modify_date


def adata(question_id):  # 댓글 정보 불러오기
    try:
        reqs = requests.get(base_url + '/answer/')
        responses = reqs.json()
        answer = []
        count = 0
        for x in range(len(responses)):
            setdata = {}
            if question_id == responses[x]['question_number']:  # 각 질문 별 댓글 처리
                count += 1
                setdata['answer_number'] = responses[x]['answer_number']  # 댓글 번호
                setdata['content'] = responses[x]['content']  # 내용
                setdata['create_date'] = responses[x]['create_date']  # 작성 날짜
                setdata['question_number'] = responses[x]['question_number']
                if not is_date_format(setdata['create_date']):
                    create_dates = parser.parse(setdata['create_date'])
                    create_date = create_dates.strftime("%Y년 %m월 %d일 %H시 %M분")
                    setdata['create_date'] = create_date
                setdata['creator'] = responses[x]['creator']
                setdata['modify_date'] = responses[x]['modify_date']
                if setdata['modify_date']:
                    if not is_date_format(setdata['modify_date']):
                        modify_dates = parser.parse(setdata['modify_date'])
                        modify_date = modify_dates.strftime("%Y년 %m월 %d일 %H시 %M분")
                        setdata['modify_date'] = modify_date
                answer.append(setdata)
    except ConnectTimeout:
        answer = None
        count = None

    return answer, count


def count(question_id):  # 질문 별 댓글 숫자 확인
    try:
        reqs = requests.get(base_url + '/answer/')
        responses = reqs.json()
        return sum(1 for data in responses if data['question_number'] == question_id)
    except ConnectTimeout:
        return None


def is_date_format(string):  # ISO 시간 값 확인
    try:
        datetime.strptime(string, "%Y년 %m월 %d일 %H시 %M분")
        return True
    except ValueError:
        return False


def change_datetime_format(date_string):  # ISO 시간 값을 년.월.일.시.분으로 변환
    if date_string:
        try:
            date_obj = parser.parse(date_string)
            return date_obj.strftime("%Y년 %m월 %d일 %H시 %M분")
        except ValueError:
            pass
    return date_string


def change():
    try:
        req = requests.get(base_url + '/question/')
        responses = req.json()
        sorted_data = []
        for data in responses:
            data['create_datetime'] = change_datetime_format(data['create_datetime'])
            data['modify_datetime'] = change_datetime_format(data['modify_datetime'])
            data['count'] = count(data['question_number'])
            sorted_data.append(data)

        sorted_data = sorted(sorted_data, key=lambda x: x['question_number'], reverse=True)
        return sorted_data
    except ConnectTimeout:
        return []


def index(request):
    if request.method == 'GET':

        page = request.GET.get('page', '1')  # 페이지
        kw = request.GET.get('kw', '')  # 검색어
        repon = change()

        new_list = []
        results = []
        for x in repon:
            new_dict = {k: v for k, v in x.items() if
                        k not in ['question_number', 'create_datetime', 'modify_datetime']}
            new_list.append(new_dict)
            if kw and any(kw in str(value) for value in new_dict.values()):
                results.append(x)

        if kw:
            repon = results
        else:
            repon = [dict(new_dict, **x) for new_dict, x in zip(new_list, repon)]

        paginator = Paginator(repon, 10)
        page_obj = paginator.get_page(page)

        if 'session' in request.COOKIES:
            session = {}
            session['session'] = request.COOKIES['session']
            responses = requests.post(base_url + '/SessionData/', data=session)
            data = responses.json()

            context = {'question_list': page_obj,
                       'page': page,
                       'kw': kw,
                       'username': data['username']
                       }
            return render(request, 'pybo/question_list.html', context)
        else:
            return redirect('common:login')


def detail(request, question_number):
    if request.method == 'GET':

        answer, count = adata(question_number)
        id, subject, content, create_date, creator, modify_date = qdata(question_number)

        if 'session' in request.COOKIES:
            body = {'session': request.COOKIES['session']}
            responses = requests.post(base_url + '/SessionData/', data=body)
            data = responses.json()
            context = {'question_number': id,
                       'question_subject': subject,
                       'question_content': content,
                       'question_modify_date': modify_date,
                       'question_creator': creator,
                       'question_create_date': create_date,
                       'AnswerAll': answer,
                       'Answer_count': count,
                       'username': data['username']
                       }
            return render(request, 'pybo/question_detail.html', context)
        else:
            return redirect('common:login')

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Smart parking</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Parking</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if username %}
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight:900" href="{% url 'common:logout' %}">{{ username }}(로그아웃)</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" style="font-weight:900" href="{% url 'camera:camera' %}">CCTV 영상</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" style="font-weight:900" href="{% url 'parking_lot:parking' %}">주차장 현황</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" style="font-weight:900" href="{% url 'log:index' %}">입출자 기록</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" style="font-weight:900" href="{% url 'visitor:visitor' %}">비등록/방문자 기록</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" style="font-weight:900" href="{% url 'warning:warning' %}">사고 기록</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" style="font-weight:900" href="{% url 'residents:residents' %}">입주자 정보</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight:900" href="{% url 'common:login' %}">로그인</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight:900" href="{% url 'common:signup' %}">회원가입</a>
                        </li>
                        {% endif %}
                    </ul>
        </div>
    </div>
</nav>