config/urls.py
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('pybo/', include('pybo.urls')),
    path('', include('common.urls')),  # '/' 에 해당되는 path
    path('camera/', include('camera.urls')),
    path('parking_lot/', include('parking_lot.urls')),
    path('logs/', include('log.urls')),
    path('visitor/', include('visitor.urls')),
    path('warning/', include('warning.urls')),
    path('residents/', include('residents.urls')),
    path('alarm/', include('alarm.urls')),
]
handler500 = 'common.views.handler500'
handler404 = 'common.views.page_not_found'

log/urls.py
from django.urls import path
from . import views

app_name = 'log'

urlpatterns = [
                  path('', views.index, name='index'),
              ]

residents/urls.py
from django.urls import path
from . import views

app_name = 'residents'

urlpatterns = [
    path('', views.residents, name='residents'),
    path('sign/', views.resident_sign, name='resident_sign'),
    path('<int:residents_number>/', views.change, name='change'),
]

residents/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
import requests
from .SendApi import send_api
from requests.exceptions import ConnectTimeout
from django.http import Http404
import concurrent.futures

base_url = 'http://3.34.74.107:8000'
headers = {
    # "Authorization": "ToKen 750b311fec4b7c0a2a023bd557a149fb1f3a5085",  # 토큰값
    "Content-Type": "application/json",
    "charset": "UTF-8",
    "Accept": "*/*",
}


def get_residents():  # 입주민 정보 가져오기
    try:
        req = requests.get(base_url + '/residents_information/')
        response = req.json()
    except ConnectTimeout:
        response = {}
    return response


def search_residents(response, kw):  # 검색시 입주민 정보 찾기
    results = []
    for resident in response:
        filtered_resident = {k: v for k, v in resident.items() if k != 'residents_number'}
        if any(kw in str(value) for value in filtered_resident.values()):
            results.append(resident)
    return results if kw else [{k: v for k, v in resident.items() if k != 'residents_number'} for resident in response]


def paginate_residents(request, response):
    page = request.GET.get('page', '1')
    paginator = Paginator(response, 10)
    page_obj = paginator.get_page(page)
    return page_obj


def get_session(request):  # 세션 정보 확인
    if 'session' in request.COOKIES:
        session = {'session': request.COOKIES['session']}
        responses = requests.post(base_url + '/SessionData/', data=session)
        data = responses.json()
        return data['username']
    else:
        return None


def residents(request):
    if request.method == 'GET':
        response = get_residents()
        kw = request.GET.get('kw', '')  # 검색어
        if kw:
            response = search_residents(response, kw)

        page_obj = paginate_residents(request, response)
        username = get_session(request)

        if username:
            context = {'resident_list': page_obj,
                       'page': page_obj.number,
                       'kw': kw,
                       'username': username,
                       }
            return render(request, 'resident/resident.html', context)
        else:
            return redirect('common:login')


def resident_sign(request):  # 회원 정보 만들기
    username = get_session(request)

    if request.method == 'GET':
        context = {'error_message': False}

        if username:
            context['username'] = username
            return render(request, 'resident/sign.html', context)
        else:
            return redirect('common:login')

    if request.method == 'POST' and username:
        body = {
            'resident_name': request.POST.get('resident_name'),  # 입주민 이름
            'resident_dong': request.POST.get('resident_dong'),  # 사는 동
            'resident_ho': request.POST.get('resident_ho'),  # 사는 호
            'residents_doorpasswd': request.POST.get('residents_doorpasswd'),  # 건물 입구 비밀번호
            'resident_homephonenumber': request.POST.get('resident_homephonenumber'),  # 집 전화 번호
            'resident_phone': request.POST.get('resident_phone'),  # 핸드폰 번호
            'resident_carnumber': request.POST.get('resident_carnumber'),  # 입주민 차 번호
            'resident_typeofcar': request.POST.get('resident_typeofcar'),  # 입주민 차량 종류
            'login_PassWd': request.POST.get('login_PassWd'),  # 앱 비밀번호
            'resident_residency': bool(request.POST.get('resident_residency')),  # 거주 여부
        }
        requests.post(base_url + '/residents_information/', data=body)

        response = get_residents()
        kw = request.GET.get('kw', '')
        if kw:
            response = search_residents(response, kw)

        page_obj = paginate_residents(request, response)

        context = {
            'resident_list': page_obj,
            'page': request.GET.get('page', '1'),
            'kw': kw,
            'username': username,
        }
        return render(request, 'resident/resident.html', context)
    else:
        return redirect('common:login')


def change(request, residents_number):  # 입주민 정보 수정
    if 'session' not in request.COOKIES:
        return redirect('common:login')

    session = {'session': request.COOKIES['session']}
    username_response = requests.post(base_url + '/SessionData/', data=session)
    username = username_response.json().get('username')

    residents = get_residents()
    resident = next((resident for resident in residents if resident['residents_number'] == residents_number), None)
    if resident is None:
        raise Http404("Resident does not exist")

    if request.method == 'GET':
        context = {'username': username, **resident}
        return render(request, 'resident/change.html', context)

    if request.method == 'POST':
        body = {
            'resident_name': request.POST['resident_name'],
            'resident_dong': request.POST['resident_dong'],
            'resident_ho': request.POST['resident_ho'],
            'residents_doorpasswd': request.POST['residents_doorpasswd'],
            'resident_homephonenumber': request.POST['resident_homephonenumber'],
            'resident_phone': request.POST['resident_phone'],
            'resident_carnumber': request.POST['resident_carnumber'],
            'resident_typeofcar': request.POST['resident_typeofcar'],
            'login_PassWd': request.POST['login_PassWd'],
            'resident_residency': bool(request.POST.get('resident_residency'))
        }

        send_api(base_url, f'/residents_information/{residents_number}', 'PUT', headers, body)

        return redirect('residents:residents')

templates/resident/change.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post">
        {% if error_message %}
            <div class="alert alert-danger" role="alert">
                <strong>등록 오류:</strong> {{ error_message }}
            </div>
        {% endif %}
        {% csrf_token %}
        <div class="mb-3">
            <label for="resident_name">입주자 이름</label>
            <input type="text" class="form-control" name="resident_name" id="resident_name"
                   value="{{ resident_name|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="resident_dong">입주자 동</label>
            <input type="text" class="form-control" name="resident_dong" id="resident_dong"
                   value="{{ resident_dong|default_if_none:'' }}">
        </div>

        <div class="mb-3">
            <label for="resident_ho">입주자 호</label>
            <input type="text" class="form-control" name="resident_ho" id="resident_ho"
                   value="{{ resident_ho|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="residents_doorpasswd">현관문 비밀번호</label>
            <input type="text" class="form-control" name="residents_doorpasswd" id="residents_doorpasswd"
                   value="{{ residents_doorpasswd|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="resident_homephonenumber">집 전화번호</label>
            <input type="text" class="form-control" name="resident_homephonenumber" id="resident_homephonenumber"
                   value="{{ resident_homephonenumber|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="resident_phone">휴대폰 전화번호</label>
            <input type="text" class="form-control" name="resident_phone" id="resident_phone"
                   value="{{ resident_phone|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="resident_phone">앱 비밀번호</label>
            <input type="text" class="form-control" name="login_PassWd" id="login_PassWd"
                   value="{{ login_PassWd|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="resident_carnumber">차량번호</label>
            <input type="text" class="form-control" name="resident_carnumber" id="resident_carnumber"
                   value="{{ resident_carnumber|default_if_none:'' }}">
        </div>
            <div class="mb-3">
            <label for="resident_typeofcar">차량 종류</label>
            <select name="resident_typeofcar" id="resident_typeofcar"
            style="background: #99ccdd;
            color: #000000;
            border: 1px solid black;
            padding: 4px;
            border-radius: 9px;
            width: 11%;">
                <option value="none">=== 선택 ===</option>
                <option value="전기">전기</option>
                <option value="휘발유">휘발유</option>
                <option value="경유">경유</option>
              </select>
        </div>
        <div class="mb-3">
            <label for="resident_residency">거주 여부</label>
            <div>
              <input type="checkbox" id="resident_residency" name="resident_residency" checked>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">수정하기</button>
    </form>
</div>
{% endblock %}

templates/resident/resident.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
            <h2 class="border-bottom py-2">입주자 정보</h2>
        <div class="col-6">
            <a href="{% url 'residents:resident_sign' %}" class="btn btn-primary">입주자 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table ">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th>입주자 이름</th>
            <th >입주자 주소</th>
            <th>현관문 비밀번호</th>
            <th>집 전화번호</th>
            <th>휴대폰 전화번호</th>
            <th>차량번호</th>
            <th>차량 종류</th>
            <th>거주 여부</th>
            <th>이사 날짜</th>
            <th>앱 비밀번호</th>
        </tr>
        </thead>
        <tbody>
        {% if resident_list %}
        {% for resident in resident_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ resident_list.paginator.count|sub:resident_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td><a href="{% url 'residents:change' resident.residents_number %}">{{ resident.resident_name }}</a></td>
            <td>{{ resident.resident_dong}}동 {{ resident.resident_ho}}호 </td>  <!-- 글쓴이 추가 -->
            <td>{{ resident.residents_doorpasswd }}</td>
            <td>{{ resident.resident_homephonenumber }}</td>
            <td>{{ resident.resident_phone }}</td>
            <td>{{ resident.resident_carnumber }}</td>
            <td>{{ resident.resident_typeofcar }}</td>
            <td>{{ resident.resident_residency }}</td>
            <td>{{ resident.resident_movedate }}</td>
            <td>{{ resident.login_PassWd }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr class = "text-center">
            <td colspan="11">정보가 없습니다.</td>
        {% endif %}
        </tbody>
    </table>
 <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if resident_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ resident_list.previous_page_number }}"
            href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in resident_list.paginator.page_range %}
        {% if page_number >= resident_list.number|add:-5 and page_number <= resident_list.number|add:5 %}
        {% if page_number == resident_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}

        <!-- 다음페이지 -->
        {% if resident_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ resident_list.next_page_number }}"
           href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->

</div>
<form id="searchForm" method="get" action="{% url 'residents:residents' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
document.getElementById("search_kw").addEventListener("keyup", function(event) {
        if (event.keyCode === 13) {
            event.preventDefault();
            document.getElementById("btn_search").click();
        }
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

templates/resident/sign.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'residents:resident_sign' %}">
        {% if error_message %}
            <div class="alert alert-danger" role="alert">
                <strong>회원가입 오류:</strong> {{ error_message }}
            </div>
        {% endif %}
        {% csrf_token %}
        <div class="mb-3">
            <label for="resident_name">입주자 이름</label>
            <input type="text" class="form-control" name="resident_name" id="resident_name"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="resident_dong">입주자 동</label>
            <input type="text" class="form-control" name="resident_dong" id="resident_dong"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>

        <div class="mb-3">
            <label for="resident_ho">입주자 호</label>
            <input type="text" class="form-control" name="resident_ho" id="resident_ho"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="residents_doorpasswd">현관문 비밀번호</label>
            <input type="text" class="form-control" name="residents_doorpasswd" id="residents_doorpasswd"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="resident_homephonenumber">집 전화번호</label>
            <input type="text" class="form-control" name="resident_homephonenumber" id="resident_homephonenumber"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="resident_phone">휴대폰 전화번호</label>
            <input type="text" class="form-control" name="resident_phone" id="resident_phone"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="resident_phone">앱 비밀번호</label>
            <input type="text" class="form-control" name="login_PassWd" id="login_PassWd"
                   value="{{ login_PassWd|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="resident_carnumber">차량번호</label>
            <input type="text" class="form-control" name="resident_carnumber" id="resident_carnumber"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
            <div class="mb-3">
            <label for="resident_typeofcar">차량 종류</label>
            <select name="resident_typeofcar" id="resident_typeofcar"
            style="background: #99ccdd;
            color: #000000;
            border: 1px solid black;
            padding: 4px;
            border-radius: 9px;
            width: 11%;">
                <option value="none">=== 선택 ===</option>
                <option value="전기">전기</option>
                <option value="휘발유">휘발유</option>
                <option value="경유">경유</option>
              </select>
        </div>
        <div class="mb-3">
            <label for="resident_residency">거주 여부</label>
            <div>
              <input type="checkbox" id="resident_residency" name="resident_residency" checked>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}